version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb-bulsarapp-server
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
        - 27018:27017
    command: mongod
    
volumes:
  mongodb:
  mongodb_config:
